project:
  type: website
  output-dir: docs

website:
  title: "homepage"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css



